# @package _global_

grpo_params:
    model_path: allenai/Olmo-3-7B-Instruct-SFT
    batch_size: 8
    gradient_accumulation_steps: 16

gen_params:
    vllm_gpu_memory_utilization: 0.3
    vllm_tensor_parallel_size: 1