# @package _global_
data:
    train: Aletheia-Bench/Aletheia-Train
    val: null
grpo_params:
    beta: 1e-3
    epsilon: 0.2
    epsilon_high: 0.28
    eval_batch_size: 16
    learning_rate: 1e-6
    logging_steps: 1
    loss_type: dapo
    lr_scheduler_type: constant_with_warmup
    max_prompt_length: 4096
    num_epochs: 1
    overwrite_output_dir: True
    save_steps: 0.1
    seed: 42
    use_bf16: True
    warmup_ratio: 0.05
    weight_decay: 1e-2
    kl_penalty: dynamic
    ref_model_sync_steps: 100
    ref_model_mixup_alpha: 1.0
    generate_every: 1
    importance_sampling_level: token
    scale_rewards: group

gen_params:
    max_completion_length: 16384
    num_generations: 16
    temperature: 1.0
    vllm_dtype: bfloat16
    vllm_max_model_length: 20480
    vllm_server_host: localhost
    vllm_server_port: 8000
    vllm_server_timeout: 600

wandb_params:
    log_level: info

grpo_reward_type: null
grpo_use_lora: false