# @package _global_

data:
    train: Aletheia-Bench/Aletheia-DPO
    val: null
    chat_template_path: null
    
dpo_params:
    learning_rate: 5e-7
    beta: 0.1
    logging_steps: 1
    lr_scheduler_type: constant_with_warmup
    max_length: 20480
    num_epochs: 1
    overwrite_output_dir: True
    save_steps: 0.25
    seed: 42
    use_bf16: True
    warmup_ratio: 0.05
    weight_decay: 1e-2
    pad_token_id: 151647

wandb_params:
    log_level: info