# @package _global_

grpo_params:
    model_path: allenai/Olmo-3-7B-Think-SFT
    batch_size: 1
    gradient_accumulation_steps: 128

gen_params:
    vllm_gpu_memory_utilization: 0.35
    vllm_tensor_parallel_size: 2