# @package _global_
data:
    chat_template_path: ./olmo_think_chat_template_dpo.jinja

dpo_params:
    model_path: allenai/Olmo-3-7B-Think-SFT
    batch_size: 1
    gradient_accumulation_steps: 8
    precompute_ref_batch_size: 2
    pad_token_id: 100277
    eos_token_id: 100265
